import "@/styles/globals.css";

import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "Tap Game",
	description: "Generated by create-t3-app",
	metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"),
	icons: [
		{ rel: "icon", url: "/favicon.ico" },
		{ rel: "icon", type: "image/png", sizes: "32x32", url: "/favicon-32.png" },
		{ rel: "icon", type: "image/png", sizes: "16x16", url: "/favicon-16.png" },
		{ rel: "apple-touch-icon", sizes: "180x180", url: "/apple-touch-icon.png" },
	],
	manifest: "/site.webmanifest",
	openGraph: {
		title: "Tap Game",
		description: "Play instantly—no install needed.",
		url: "/",
		siteName: "Tap Game",
		images: [
			{
				url: "/og-1200x630.png",
				width: 1200,
				height: 630,
				alt: "Tap Game preview",
			},
		],
		type: "website",
	},
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}

// Future expansion (Next.js layout):
// - Add global Providers here (theme, auth UI, analytics). Wrap inside <body>.
// - Inject global fonts via next/font and apply to <html>/<body>.
// - Set metadata fields (open graph, icons, themeColor) in `metadata` above.
// - Add <head> tags (e.g., favicons) via `metadata` or a Head component if needed.
