import "@/styles/globals.css";

import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}

// Future expansion (Next.js layout):
// - Add global Providers here (theme, auth UI, analytics). Wrap inside <body>.
// - Inject global fonts via next/font and apply to <html>/<body>.
// - Set metadata fields (open graph, icons, themeColor) in `metadata` above.
// - Add <head> tags (e.g., favicons) via `metadata` or a Head component if needed.
